### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by raknash** [BennyThadikaran/BseIndiaApi#1]
Ater running for package for BSE Announcements' output generation, the subject error is thrown viz. TypeError: 'type' object is not subscriptable.  Please help in resolving

**Comment by BennyThadikaran** [comment]
Can you provide me the line that caused the error. The return type of announcements is a Dictionary. If you're trying to access it as a List you will get this error. 

See a [sample JSON](https://github.com/BennyThadikaran/BseIndiaApi/blob/main/src/samples/announcements.json) from `bse.announcements`

```python
res = bse.announcements(page_no=1)

# res is a dict, res[0] will throw TypeError: 'type' object is not subscriptable

# To get first announcement
print(res['Table'][0]

# To loop over announcements
for ann in res['Table'][0]:
    print(ann)
```

If this doesnt help, show me the code you're running. I'll be happy to help.

**Comment by raknash** [comment]
Thanks for replying.  This error is not cropping up now.  However, I get the following set of errors.  I am not a programmer and hence please accept my apology if I am highlighting trivial errors that could be easily addressed by persons having basic knowledge of python;

4.1%8.2%12.3%16.39%Traceback (most recent call last):

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\connectionpool.py:537 in _make_request
    response = conn.getresponse()

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\connection.py:461 in getresponse
    httplib_response = super().getresponse()

  File C:\Users\Public\Anaconda3\Lib\http\client.py:1386 in getresponse
    response.begin()

  File C:\Users\Public\Anaconda3\Lib\http\client.py:325 in begin
    version, status, reason = self._read_status()

  File C:\Users\Public\Anaconda3\Lib\http\client.py:286 in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File C:\Users\Public\Anaconda3\Lib\socket.py:706 in readinto
    return self._sock.recv_into(b)

  File C:\Users\Public\Anaconda3\Lib\ssl.py:1315 in recv_into
    return self.read(nbytes, buffer)

  File C:\Users\Public\Anaconda3\Lib\ssl.py:1167 in read
    return self._sslobj.read(len, buffer)

TimeoutError: The read operation timed out


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File C:\Users\Public\Anaconda3\Lib\site-packages\requests\adapters.py:486 in send
    resp = conn.urlopen(

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\connectionpool.py:845 in urlopen
    retries = retries.increment(

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\util\retry.py:470 in increment
    raise reraise(type(error), error, _stacktrace)

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\util\util.py:39 in reraise
    raise value

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\connectionpool.py:791 in urlopen
    response = self._make_request(

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\connectionpool.py:539 in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)

  File C:\Users\Public\Anaconda3\Lib\site-packages\urllib3\connectionpool.py:371 in _raise_timeout
    raise ReadTimeoutError(

ReadTimeoutError: HTTPSConnectionPool(host='api.bseindia.com', port=443): Read timed out. (read timeout=10)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File C:\Users\Public\Anaconda3\Lib\site-packages\bse\BSE.py:99 in __req
    response = self.session.get(url, params=params, timeout=timeout)

  File C:\Users\Public\Anaconda3\Lib\site-packages\requests\sessions.py:602 in get
    return self.request("GET", url, **kwargs)

  File C:\Users\Public\Anaconda3\Lib\site-packages\requests\sessions.py:589 in request
    resp = self.send(prep, **send_kwargs)

  File C:\Users\Public\Anaconda3\Lib\site-packages\requests\sessions.py:703 in send
    r = adapter.send(request, **kwargs)

  File C:\Users\Public\Anaconda3\Lib\site-packages\requests\adapters.py:532 in send
    raise ReadTimeout(e, request=request)

ReadTimeout: HTTPSConnectionPool(host='api.bseindia.com', port=443): Read timed out. (read timeout=10)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File C:\Users\Public\Anaconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File d:\python\bse data download\get_all_announcements.py:21
    res = bse.announcements(page_no=page_count)

  File C:\Users\Public\Anaconda3\Lib\site-packages\bse\BSE.py:290 in announcements
    return self.__req(url, params).json()

  File C:\Users\Public\Anaconda3\Lib\site-packages\bse\BSE.py:101 in __req
    raise TimeoutError('Request timed out')

TimeoutError: Request timed out

As per my limited understanding, the first error has spawned the subsequent ones and ended up as a timed out error.

**Comment by BennyThadikaran** [comment]
A ReadTimeout occurs when the server fails to respond within a fixed time.

You can refer [this code in BSE.py](https://github.com/BennyThadikaran/BseIndiaApi/blob/main/src/bse/BSE.py#L97). The timeout is 10 seconds. If there is no reponse from BSE server within 10 seconds, a TimeoutError occurs.

There is likely nothing wrong with your code. It can occur due to various reasons. Just retry the code and let me know if it happens repeatedly.

You can also try and catch these error if you dont want to see the error trace.

```python
try:
    res = bse.announcements(page_no=page_count)
except TimeoutError as e:
    # or do something else
    exit(e)
```

You can reach out to me over telegram if you have questions. Ofcourse you can raise an issue anytime. 

No need to apologise for asking questions. It how we all learned. I am grateful to everyone, taking interest in my code.

**Comment by raknash** [comment]
Thanks a lot.  Now it works like a charm.  I did try to download more than once before posting the error list; but somehow it showed the same set of errors last time.  For any logical Qs, I shall connect with you via Telegram.  Thanks again.
