### ISSUE TITLE
line 2, in <module>     from requests import Session ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by TechieSik** [BennyThadikaran/BseIndiaApi#3]
Getting error in BSE.py 

, line 2, in <module>
    from requests import Session
ModuleNotFoundError: No module named 'requests'

Already installed request module

**Comment by BennyThadikaran** [comment]
Are you using [python venv](https://docs.python.org/3/library/venv.html) or some other virtual env?  Perhaps you forgot the activate the environment before running the code. 

Run `pip list` and check if `requests` is listed in the installed packages. Are you using Windows or Linux/mac?

**Comment by TechieSik** [comment]
Hi Benny,
I appreciate your response.

I am using Python 3.+ In Windows, no virtual env I guess.
How to activate env ?

Using Pip list I see requests 2.32.3 is installed.

Regards 
Sik

**Comment by TechieSik** [comment]
This is now solved after installing requests in pip3.
But now after executing BSE.py I am getting now put, can you assign ?

**Comment by BennyThadikaran** [comment]
>  But now after executing BSE.py I am getting now put, can you assign ?

I didnt understand this.
